### ISSUE TITLE
Municípios estão com erro de codificação

### ISSUE THREAD

**Issue by fabianogadenz** [rodrigobastosv/estados_municipios#2]
Boa tarde, notei que os municípios estão com erro de codificação, seria possível mudar para UTF-8? 

![image](https://user-images.githubusercontent.com/12851596/141136410-c06453d4-63a9-4e92-9c82-f91c6f7caed8.png)

**Comment by rodrigobastosv** [comment]
Oi @fabianogadenz , obrigado por usar este pacote!

Vou checar!

**Comment by rodrigobastosv** [comment]
@fabianogadenz , desculpa a demora, acabei nao vendo a atualizacao dessa issue.

Para mim ta funcionando perfeitamente. Ainda está com problema para voce? Se sim, pode me passar um pequeno exemplo para eu reproduzir aqui?

Muito obrigado!

**Comment by rodrigobastosv** [comment]
Fechando a issue por inatividade. Fica a vontade para abrir se ainda for necessário!
