### ISSUE TITLE
Id do município com tipo errado

### ISSUE THREAD

**Issue by ricardosohn** [rodrigobastosv/estados_municipios#3]
Quando eu rodo a função de pegar a lista de municípios por estado, ocorre um erro no método Municipio.fromJson().
Trata-se de um erro de tipo, a API retorna String no campo 'id' e o método tenta interpretar como um inteiro.

https://github.com/rodrigobastosv/estados_municipios/blob/dd166da1af43b8bfb167de9677011cc7682fa825/lib/src/model/municipio.dart#L5

**Comment by rodrigobastosv** [comment]
Oi Ricardo, obrigado por usar este pacote!

Qual estado voce esta testando para eu tentar simular aqui?

**Comment by ricardosohn** [comment]
Testei com SC e mais alguns, todos retornaram String.

Flutter doctor -v
```
[√] Flutter (Channel stable, 2.10.0, on Microsoft Windows [versÃ£o 10.0.19044.1586], locale pt-BR)
    • Flutter version 2.10.0 at E:\flutter
    • Framework revision 5f105a6ca7 (8 weeks ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

```

**Comment by rodrigobastosv** [comment]
Vlw @ricardosohn , aparentemente a API que eu uso mudou o tipo do ID.

Já fiz o ajuste e ja esta disponivel na versao 2.0.0+3, já no pub.dev.

Muito obrigado!

Vou fechar a issue, mas fica livre para reabrir se tiver alguma duvida
