### ISSUE TITLE
'int' is not a subtype of type 'String?' na recuperação de municípios 

### ISSUE THREAD

**Issue by Greismorr** [rodrigobastosv/estados_municipios#4]
Ao buscar os municípios, o pacote está retornando o erro `'int' is not a subtype of type 'String?' `.

![image](https://user-images.githubusercontent.com/55334621/190192138-d30ece89-20b2-445a-9f20-29ea101ce550.png)

**Comment by rodrigobastosv** [comment]
Obrigado por usar este pacote @Greismorr !

Eu acredito que o campo vem como inteiro mesmo. Acho que já tinha feito essa mudança mas esqueci de atualizar o pacote no pub.dev.

Pode tentar novamente na versao 2.0.1 do package? Acabei de publicar no pub.dev

**Comment by Greismorr** [comment]
Olá, @rodrigobastosv .

Acabei de testar e o problema foi resolvido, mas o pacote agora está printando o runtimeType no método de desserialização dos municípios.

Obrigado pela velocidade :)!

**Comment by rodrigobastosv** [comment]
Show! Tinha colocado um print pra debugar e acabei comitando.

Por gentileza pega a versao 2.0.1+1. Acabei de publica.

Novamente obrigado por usar o pacote :)
